In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Dataset/data.csv")
data.head()

,Unnamed: 0,id,conversation_id,tweet,replies_count,retweets_count,likes_count,annotator_label_1,annotator_label_2,annotator_label_3,final_label,target,confidence_score
0,0,1.622571e+10,1.622571e+10,Whenever it gets close to my bday I always go ...,0,0,0,0,0,1,0,non-depressed,0.67
1,1,2.951188e+10,2.951188e+10,". Yeah, I can see that. My stuff is not depres...",0,0,0,0,0,0,0,non-depressed,1.00
2,2,5.290000e+17,5.290000e+17,My focus has been scattered lately between dif...,0,0,0,1,1,1,1,mild,1.00
3,3,6.540000e+17,6.540000e+17,"I don't always think it equals depression, tho...",1,0,1,0,0,0,0,non-depressed,1.00
4,4,8.600000e+17,8.600000e+17,That show was ghastly! It had such an air of w...,1,0,0,0,0,0,0,non-depressed,1.00

In [4]:
data = data[['tweet', 'target', 'final_label']]
data.head()

,tweet,target,final_label
0,Whenever it gets close to my bday I always go ...,non-depressed,0
1,". Yeah, I can see that. My stuff is not depres...",non-depressed,0
2,My focus has been scattered lately between dif...,mild,1
3,"I don't always think it equals depression, tho...",non-depressed,0
4,That show was ghastly! It had such an air of w...,non-depressed,0

In [7]:
data = data.rename(columns = {"tweet":"text","target":"label","final_label":"target"})
data.head()

                                                text          label  target
0  Whenever it gets close to my bday I always go ...  non-depressed       0
1  . Yeah, I can see that. My stuff is not depres...  non-depressed       0
2  My focus has been scattered lately between dif...           mild       1
3  I don't always think it equals depression, tho...  non-depressed       0
4  That show was ghastly! It had such an air of w...  non-depressed       0

In [8]:
data.to_csv('Dataset/final_data.csv')