In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Dataset/data.csv")
data.head()

,Unnamed: 0,id,conversation_id,tweet,replies_count,retweets_count,likes_count,annotator_label_1,annotator_label_2,annotator_label_3,final_label,target,confidence_score
0,0,1.622571e+10,1.622571e+10,Whenever it gets close to my bday I always go ...,0,0,0,0,0,1,0,non-depressed,0.67
1,1,2.951188e+10,2.951188e+10,". Yeah, I can see that. My stuff is not depres...",0,0,0,0,0,0,0,non-depressed,1.00
2,2,5.290000e+17,5.290000e+17,My focus has been scattered lately between dif...,0,0,0,1,1,1,1,mild,1.00
3,3,6.540000e+17,6.540000e+17,"I don't always think it equals depression, tho...",1,0,1,0,0,0,0,non-depressed,1.00
4,4,8.600000e+17,8.600000e+17,That show was ghastly! It had such an air of w...,1,0,0,0,0,0,0,non-depressed,1.00

In [4]:
data = data[['tweet', 'target', 'final_label']]
data.head()

,tweet,target,final_label
0,Whenever it gets close to my bday I always go ...,non-depressed,0
1,". Yeah, I can see that. My stuff is not depres...",non-depressed,0
2,My focus has been scattered lately between dif...,mild,1
3,"I don't always think it equals depression, tho...",non-depressed,0
4,That show was ghastly! It had such an air of w...,non-depressed,0

In [7]:
data = data.rename(columns = {"tweet":"text","target":"label","final_label":"target"})
data.head()

                                                text          label  target
0  Whenever it gets close to my bday I always go ...  non-depressed       0
1  . Yeah, I can see that. My stuff is not depres...  non-depressed       0
2  My focus has been scattered lately between dif...           mild       1
3  I don't always think it equals depression, tho...  non-depressed       0
4  That show was ghastly! It had such an air of w...  non-depressed       0

In [8]:
data.to_csv('Dataset/dataset.csv')

In [2]:
data = pd.read_csv('Dataset/dataset.csv')
data.head(10)

,Unnamed: 0,text,label,target
0,0,Whenever it gets close to my bday I always go ...,non-depressed,0
1,1,". Yeah, I can see that. My stuff is not depres...",non-depressed,0
2,2,My focus has been scattered lately between dif...,mild,1
3,3,"I don't always think it equals depression, tho...",non-depressed,0
4,4,That show was ghastly! It had such an air of w...,non-depressed,0
5,5,Am unsure where begin. My focus is scattered. ...,mild,1
6,6,Stress &amp; anxiety had me withdrawn from the...,moderate,2
7,7,These spirits had me lifted when I was low spi...,non-depressed,0
8,8,"My kids say this to me now, after 12yrs of , b...",mild,1
9,9,Help me figure out the truth behind this. Dep...,non-depressed,0

In [5]:
data = data.drop(labels=['Unnamed: 0'], axis=1)
data.head()

                                                text          label  target
0  Whenever it gets close to my bday I always go ...  non-depressed       0
1  . Yeah, I can see that. My stuff is not depres...  non-depressed       0
2  My focus has been scattered lately between dif...           mild       1
3  I don't always think it equals depression, tho...  non-depressed       0
4  That show was ghastly! It had such an air of w...  non-depressed       0

In [10]:
data_0 = data[data['target'] == 0]
data_1 = data[data['target'] == 1]
data_2 = data[data['target'] == 2]
data_3 = data[data['target'] == 3]

print(len(data)==(len(data_0)+len(data_1)+len(data_2)+len(data_3)))

True

In [19]:
from sklearn.model_selection import train_test_split
def train_validate_test_split(df, seed = 7):
    train, valtest = train_test_split(df, test_size=0.4, random_state = seed)
    val, test = train_test_split(valtest, test_size = 0.5, random_state = seed)
    return train, val, test

train_df_0, valid_df_0, test_df_0 = train_validate_test_split(data_0)
train_df_1, valid_df_1, test_df_1 = train_validate_test_split(data_1)
train_df_2, valid_df_2, test_df_2 = train_validate_test_split(data_2)
train_df_3, valid_df_3, test_df_3 = train_validate_test_split(data_3)

train_df = train_df_0 + train_df_1 + train_df_2 + train_df_3
valid_df = valid_df_0 + valid_df_1 + valid_df_2 + valid_df_3
test_df = test_df_0 + test_df_1 + test_df_2 + test_df_3

print(len(data)==(len(train_df)+len(valid_df)+len(test_df)))
                  
train_df.to_csv('train.csv')
valid_df.to_csv('valid.csv')
test_df.to_csv('test.csv')

True

In [22]:
print(set(data.label))
print(set(data.target))

{'moderate', 'mild', 'non-depressed', 'severe'}
{0, 1, 2, 3}